# Generated by Django 5.0.7 on 2024-08-02 07:43

import base.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[base.models.validate_non_negative])),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, validators=[base.models.validate_non_negative])),
                ('currency', models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('ALL', 'L')], default='ALL', max_length=5)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[base.models.validate_non_negative])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product/')),
                ('is_discount', models.BooleanField(default=False)),
                ('out_of_sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory'),
        ),
    ]
