# Generated by Django 5.0.7 on 2024-07-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
        ),
    ]
