# Generated by Django 5.0.7 on 2024-07-27 08:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[base.models.validate_non_negative]),
        ),
    ]
