# Generated by Django 5.0.7 on 2024-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_product_discont_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_sale',
            field=models.BooleanField(default=False),
        ),
    ]
