# Generated by Django 5.0.7 on 2024-08-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_product_subcategory_delete_costumer_and_more'),
        ('base', '0015_product_out_of_sale'),
    ]

    operations = [
    ]
