# Generated by Django 5.0.7 on 2024-07-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_out_of_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='usage',
        ),
    ]
