# Generated by Django 5.0.7 on 2024-07-28 14:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_out_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, validators=[base.models.validate_non_negative]),
        ),
    ]
