# Generated by Django 5.0.7 on 2024-07-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_name_alter_product_new_price'),
        ('base', '0016_remove_product_usage'),
    ]

    operations = [
    ]
