# Generated by Django 5.0.7 on 2024-08-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_product_subcategory_delete_costumer_and_more'),
        ('base', '0019_alter_wishlist_unique_together'),
    ]

    operations = [
    ]
