# Generated by Django 5.0.7 on 2024-08-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20240819_1448'),
        ('base', '0019_alter_wishlist_unique_together'),
    ]

    operations = [
    ]
