# Generated by Django 5.0.7 on 2024-08-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_costumer_product_category_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
