# Generated by Django 5.0.7 on 2024-08-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_costumer_alter_wishlist_user'),
        ('base', '0020_merge_20240802_1044'),
        ('base', '0021_alter_category_options'),
    ]

    operations = [
    ]
